import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/lib/StoreProvider";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={rubik.className}>{children}</body>
      </html>
    </StoreProvider>
  );
}
